export const environment = {
  production: true,
  artists_service_base_url: "http://localhost:3000/api",
  app_title: "angular-ui",
  artist_id: "artistId",
  song_id: "songId",
  auth_header: "Authorization",
  token_key: "token",
  defaultPageSize: 5,

  welcome_message: "Welcome to MEAN Rock Music Artists",
  copyright_message: "Maharishi International University. All Rights Reserved.",

  greeting_label: "Hello",
  login_label: "Login",
  logout_label: "Logout",
  username_label: "Username",
  password_label: "Password",
  confirm_label: "Confirm",

  home_label: "Home",
  profile_label: "Profile",

  add_label: "Add",
  update_label: "Update",
  ok_label: "Ok",
  cancel_label: "Cancel",
  next_label: "Next",
  previous_label: "Previous",
  edit_label: "Edit",
  delete_label: "Delete",
  register_label: "Register",
  reset_label: "Reset",

  name_label: "Name",
  bornYear_label: "Born year",
  gender_label: "Gender",
  nation_label: "Nation",
  firstSong_label: "First song",
  bands_label: "Bands",
  location_label: "Location",
  songs_label: "Songs",

  page_label: "Page",
  artist_label: "Artist",
  artists_label: "Artists",
  display_total_label: "Displaying total",
  records_label: "records",
  of_label: "of",

  list_label: "list",

  title_abel: "Title",
  rank_abel: "Rank",
  year_label: "Year",
  album_label: "Album",

  search_label: "Search",
  latitude_label: "Latitude",
  longitude_label: "Longitude",
  minimum_label: "Minimum",
  maximum_label: "Maximum",
  distance_label: "Distance",
  geoSearch_label: "Geo Search",
  by_label: "by",
  for_label: "for",

  artist_add_success_message: "New artist added successfully.",
  artist_add_fail_message: "Failed to add new artist!",
  artist_update_success_message: "Artist updated successfully.",
  artist_update_fail_message: "Failed to update artist!",
  song_add_success_message: "New song added successfully.",
  song_add_fail_message: "Failed to add new song!",
  song_update_success_message: "Song updated successfully.",
  song_update_fail_message: "Failed to update song!",
  artist_delete_success_message: "Artist deleted successfully.",
  artist_delete_fail_message: "Failed to delete artist!",
  user_register_success_message: "New user registered successfully.",
  user_register_fail_message: "Failed to register new user!",

  confirm_delete_message: "Are you sure to delete?"
};
